### ISSUE TITLE
GDPR template requires title page

### ISSUE THREAD

**Issue by Andonome** [passamo9/LaTeX_EnglandWales_Templates#29] opened 2021-02-15 21:32 UTC
Hi @passamo9 - here's the separate issue for the title page of the GDPR template. Separate issues help keeping noise-to-signal ratio in proportion.

**Comment by passamo9** [comment] 2021-02-15 21:37
Perfect, thank you! As you may have gathered, I am a GitHub newb and this is all very new for me. I really appreciate the help, and especially the patience.

Would you like for me to re-post the GDPR title page picture?

The proportions are not crucial - the two elements just need to be in approximately the centre of the document, with some space in between.

**Comment by Andonome** [comment] 2021-02-15 21:38
![image](https://user-images.githubusercontent.com/52453904/107995232-7c136200-6fde-11eb-8a57-4abc3578ce42.png)

Good to know.

I'll send over an example once it's done.

**Comment by passamo9** [comment] 2021-02-15 21:44
Thank you so much @Andonome!!

**Comment by Andonome** [comment] 2021-02-15 22:08
@yjyao - it looks like my merge request for this has failed.  I've not seen Github CI's before, but I think it might be something to do with using Xelatex instead of pdflatex.

I think I could learn Xelatex, but is there any particular reason for it?  It tends to be slower, and I've heard it doesn't make results quite as neatly as basic Latex. I could be wrong on that second point, as I've not tried it much.

**Comment by yjyao** [comment] 2021-02-15 22:39
which merge request? do you have a pointer?

i thought XeLaTeX was mostly compatible with pdfLaTeX (idk, i haven't used pdfLaTeX since 2012). what did you use that XeLaTeX didn't like?

should probably be fine to switch to pdfLaTeX, unless UTF-8 or custom font is needed.

@passamo9 
1. is there _any_ case where non-latin characters (CJK, Arabic, etc.) might be used in the docs? 
2. are there any font requirements?

**Comment by passamo9** [comment] 2021-02-15 22:55
1. Never say never, I suppose. How much does that change things?
2. No formal font requirements, apart from it being legible ([which means lawyers must use common sense](https://www.civillitigationbrief.com/2017/11/05/fonts-lawyers-and-the-rules-never-ever-use-comic-sans/)). I think lawyers tend to go with Arial, Times New Roman, Century, Garamond, etc. fonts. No hard and fast rules like in the US for some circuits—only Century is accepted

**Comment by bond7o6** [comment] 2021-02-15 23:15
> non-latin characters

Wouldn't this be entirely on the side of the client side (the lawyers making the documents)? It shouldn't really matter which one we use for the CI as long as our example files aren't incompatible.

> fonts

We could implement a reasonable standard within the class if there aren't any requirements, beyond not being horrific. Then if someone wants theirs to be different, they can do that (god help them). 

> [which means lawyers must use common sense](https://www.civillitigationbrief.com/2017/11/05/fonts-lawyers-and-the-rules-never-ever-use-comic-sans/)
This is useful, we'll need to remember to put `\linespread{1.6}` everywhere. Though for a book on typography, the website for [Typography for Lawyers](https://typographyforlawyers.com/) doesn't look particularly attractive to me. Though I'll see if I can find a copy for reference, or if it has any nice ideas we might not pick up.

**Comment by yjyao** [comment] 2021-02-15 23:19
> shouldn't really matter which one we use for the CI

but @Andonome is saying their commit breaks XeLaTeX builds and need to switch to pdfLaTeX, meaning we will only support pdfLaTeX users going forward (which may or may not be desirable).

**Comment by passamo9** [comment] 2021-02-15 23:35
>Wouldn't this be entirely on the side of the client side (the lawyers making the documents)? It shouldn't really matter which one we use for the CI as long as our example files aren't incompatible.

This is very true.

>We could implement a reasonable standard within the class if there aren't any requirements, beyond not being horrific.

That sounds great!

>Then if someone wants theirs to be different, they can do that (god help them).

😂😂

>Though for a book on typography, the website for Typography for Lawyers doesn't look particularly attractive to me.

I've read it as well, and I thought it would be a great coffee table book for any lawyer friends you have 😁

>Though I'll see if I can find a copy for reference, or if it has any nice ideas we might not pick up.

I would not check on Libgen, if you get my drift

**Comment by bond7o6** [comment] 2021-02-15 23:43
> but @Andonome is saying their commit breaks XeLaTeX builds and need to switch to pdfLaTeX, meaning we will only support pdfLaTeX users going forward (which may or may not be desirable).

I don't know what the issue is with their file not building. I was building my `opinion.tex` with pdfLaTeX and that tranisitioned fine, and I don't see anything in their file that doesn't work with XeLaTeX, except that they don't seem to have included a `.sty` file, `data.sty`. I ran it with pdflatex (I think), xetex, and luatex, and the only issue was the missing file. It doesn't build but the only problem seems to be `data.sty`.

**Comment by Andonome** [comment] 2021-02-16 00:15
> but @Andonome is saying their commit breaks XeLaTeX builds and need to switch to pdfLaTeX,

@yjyao  I'm more saying we'll need to pick a lane. I think I can learn XeLaTeX, as I hear it's pretty close to pdflatex.

> I don't know what the issue is with their file not building.

Sorry! I just hunted down the problem - I'd put .sty in my .gitignore_global years ago.  I've just committed the .stye file in 481654ef5a945de18e562e7

**Comment by Andonome** [comment] 2021-02-16 00:17
As to special characters, pdflatex can handle them, you just import a package.

For European stuff like Polish and Spanish, it works fine.  I've not tried Arabic, but I suspect any non Latin-based characters would not work.

**Comment by yjyao** [comment] 2021-02-16 00:24
i don't think there's anything particular that you need to _learn_ about XeLaTeX. just write the docs as usual and you shouldn't expect many problems as @bond7o6 also said.

is your file building with XeLaTeX now?

**Comment by bond7o6** [comment] 2021-02-16 00:24
I don't think we need to pick a lane though. Your document builds fine (with the style file) with pdflatex, xetex, luatex, and something called omega (no idea). As long as we don't include anything standard that requires one of them and breaks with another (not very difficult to avoid) we can maintain compatibility with them all.

**Comment by Andonome** [comment] 2021-02-16 02:40
@passamo9 - if the title page looks good, time to close the issue.

Otherwise, another it's time for another list of fixes.

**Comment by bond7o6** [comment] 2021-02-16 03:35
Given that the PR is still open, probably close this issue anyway and raise the issues over there.

**Closed** 2021-02-16 03:35 UTC
